---
title: "Project Proposal Feedback"
author: "Xiongtao Dai"
ratio: 16x10
output:
  rmdshower::shower_presentation:
    self_contained: false
    katex: true
    theme: ribbon
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
library(tidyverse)
```

## Final Project {.shout}

## Topics

Team 1 | Team 2 | Team 3 | Team 4 
:------:|:------:|:------:|:------:
Melbourne Housing | Work-life Balance in America | US Traffic Accidents | Spotify Music 

Team 5 | Team 6 | Team 7 | Team 8 
:------:|:------:|:------:|:------:
Stroke Prediction | COVID Vaccine Distribution | COVID Vaccination | Tracking COVID Data

Team 9 | Team 10 
:------:|:------:
Cereal Nutrition | Spotify Music 

## Project Plans

- A lot of intereting datasets!
- Start easy, and divide tasks. Each teammate can look at one aspect of data. 
- Coordinate the aspects to tell a coherent story
- Introduce the background to the audiences

## Project analysis

Thing to try for an interesting analysis:

- Look at different aspects of the data: spatial, temporal, changes, extremes, outliers
- Factor in other variables for making fair comparisons
- Use multiple tools and types of graphs
- Combine data sources

## Start early!  {.shout}

## Project Requirements {.shout}

## Project Presentation
- Each team has 15 minutes
- Timing is **very important**. Make sure your team presentation is at most 1 minute long or short.
- Ideally, your presentation should contain a nicely made, information-rich visualization as the featured infographics. Make sure everything is legible as well!
- Organization, delivery, content, and timing: each 25%

## Presentation Format
- You will record the presentation 
  - Canvas studio
  - Zoom
- The recorded presentations are to be played during the scheduled time live
- After each presentation, the audiences have 5 minutes to interact with the presenters by asking questions and making comments. Questions/comments will be made in the class Zoom session. Counted towards participation. 
- The class is expected to attend all presentations.
- [Feedback](https://forms.gle/n8mShwDhfwTXSrs26) will be sought from the audiences after the presentation. This will be part of the evaluation.


## A good presentation should inform the audiences ...

- the background of the dataset
- what are the questions raised
- findings and answers
- how to obtain the data
- techniques used to handle the data

## A good presentation should

- be well-organized
- have smooth delivery
- inform on many different aspect of the data
- utilize different tools to explore the data
- have pretty and informative graphs and slides

## Final Project Report

- Tell the story, not only the coding
- The report should be as readable as a blog post
- The total number of figures and tables **should not exceed 10**. Include only the most interesting results, and condense information in each figure
- Each figure, table, or analysis must be accomanied by explanatory text
- Report is due on 11:59 pm, May 5.


## Some Other Requirements

- All teammates need to participates. Each will write a paragraph detailing the individual contribution to the team.
- Analysis need to be done in `R` only.
- All sources need to be cited.
- Cannot repeat existing analysis on the web.