---
title: 'Homework #4'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Flight data

The `nycflights13` package contains information regarding the flights that departed New York City in 2013. Use `help(package='nycflights13')` to see what datasets does the package contain. Read the documentations to get a better idea what are the datasets abouts. In this homework, we are going to focus on the `airports`, `flights`, and `weather` datasets. If you would like to know more  about this dataset and the different join functions, you can refer to the optional reading of this module.

For all of the questions in this homework, use `dplyr` functions, joins, and the pipe `%>%` as much as possible.

1. Find if each flight number is being used only once in each day. There should be one row/record per flight number. (Hint: You may need the `any()` function).

2. Add the location of *both* the origin *and* destination (i.e. the `lat` and `lon`) to `flights`. Retain only columns for the airport code, airport name, longitude, and latitude. Name the columns in a user-friendly manner.

3. Create appropriate numerical and/or graphical summaries to investigate how visibility condition makes it more likely to see a delay. Make sure to also investigate the flight delays with missing visibility values. (Hint: use `left_join`)

4. Which 5 destination airports have the most severe arrival delay? The severity of delay is defined as the proportion of arriving flights that have no less than 30 minutes arrival delay. To give you a formula, proportion of delayed flights = the number of delayed flights / the total number of flights. Create a data frame containing their airport name, code, and the severity of delay.

5. What happened on June 13, 2013? Look at the delay severity by airport on that day, and then use Google to cross-reference with the weather.
