---
title: 'Homework #6'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Top dogs

In this homework, you will reproduce the fantastic infographic for [top dogs](https://informationisbeautiful.net/visualizations/best-in-show-whats-the-top-data-dog/), originally produced by David McCandless. The raw data can be found [here](https://docs.google.com/spreadsheets/d/1l_HfF5EaN-QgnLc2UYdCc7L2CVrk0p3VdGB1godOyhk/edit#gid=10). You can download this file by clicking File -- Download As -- Microsoft Excel (.xlsx).

1. Import the data and clean appropriately. To read in the data, you can use `readxl::read_xlsx('fileNameHere', sheet='sheetNameHere')`. Required data are in the sheets `Best in show` and `Best in show full sheet`. Take extra care on the column names and the first few rows of the data frame after reading it in.

2. Create a graphics similar to the  [top dogs](https://informationisbeautiful.net/visualizations/best-in-show-whats-the-top-data-dog/) figure. Your figure will display the following information using appropriate plotting elements:

- breed of dog
- type of dog (work, toy, etc.)
- size of dog
- data score 
- popularity
- intelligence of the dog
- appropriate legends & explanation

Hints and Notes:

- The breed of dog can be displayed without the silhouttes (text only is fine)
- Avoid (too much) overlaps!
- Choose a good color scheme.
