---
title: "DS 202 - lab #3: Exploring General Social Survey"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Outline

- Optionally, team up with at most two partners from your study group
- Create a repository (one per team) & give access to your teammate(s)
- For a refreshment of git & github, review the procedures for collaboration for Lab 2.
- Explore what leads to happiness using data from the General Social Survey
- Create an R markdown file that contains all code to read the data, create the plots, and your answers.
- Teammates will review and revise each other's work.
- Submit!


## Submission Requirements

- A team member should create a GitHub repository called `ds202_lab3` which includes the group work.
- The team will collaborate on `team.Rmd` to answer all the questions (for the final report), and also include your individual exploration in `individual1.Rmd`, `individual2.Rmd`, or `indivisual3.Rmd` ("your scratch file"). **Only the report generated from `team.Rmd` will be graded.**
- Include the data you used in your repository.
- The correct folder structure is as below. The folder `ds202_lab3` is a git repository.

    ```
    ds202_lab3
    |-- individual1.Rmd
    |-- (individual2.Rmd)
    |-- (individual3.Rmd)
    |-- team.Rmd
    |-- *.html
    |-- Data files
    ```
- **From this lab forward, if you team up, each team member should create at least one commit with message "Review and Revision", which include revisions on the analysis of your partner's.**

## Background

The General Social Survey (GSS) has been run by NORC since 1972 to keep track of current opinions across the United States. One of the central question is what kind of persons tend to be happier than the others.

There is a data explorer which let you to interactively explore and extract the data here https://gssdataexplorer.norc.org/

## Part zero: Exploring the GSS data

You can search for information you are interested in under in Keyword search box. Try "happiness". If you do not find desired result, click View all Results at the bottom of the pop up menu. 
<!-- Discuss on the interesting findings within your study group. -->

We will be exploring variables related to 

- **Happiness**
- **Marital status**
- **Ecudation**
- **Political party affilation**
- Many other possible topics, such as work hours and belief -- it is up to you

## Part one: Extracting and loading data

1. Go to https://gssdataexplorer.norc.org/
2. Click Search variable
3. Search "happy"; click add to cart; go back. Repeat for "marital status", "highest year of school completed", "respondents sex", "political party affiliation", and other variables (you decide)
4. After you finished adding the variables, click Actions -- Save to Project
5. Register an account
6. Click Default Project
7. Click Actions -- Extract data
8.  a. Name your extract (e.g., extract1) -- click NEXT; 
    b. ADD ALL variables -- click NEXT; 
    c. click NEXT; 
    d. **Check Excel Workbook (data + metadata) and  Excel Workbook (metadata only), and leave all others unchecked**; 
    e. CREATE EXTRACT
9. Wait for the extract to be ready in a few minutes, and then download an archive file. 
10. Extract the archive file (ending with .tar.gz). Windows users: You may need [7-Zip](https://www.7-zip.org/)
11. Load the Excel file into R, using 
  ```
  install.packages('readxl')
  dat <- readxl::read_xls('PATH_TO_EXL/GSS.xls')
  ```

## Part two: Exploration

Use `ggplot2` to create the plots, and `dplyr` to manipulate the data frame as much as possible.  You may want to rename the columns of the data frame for your convenience using `rename` in `dplyr`.

1. Find the average years of education for the respondents with each marital status. Arrange your output in a meaningful order and print. Describe any patterns you find.
2. Create a single data frame containing records for the better educated respondents with each marital status. A "better educated" respondent is someone who has strictly more years of education than the average among those with the same marital status. Print the structure of the data frame.

  For each of the investigation below, create at least one numerical summary and one appropriate visualization. Write a paragraph to describe your findings and the variables you used.

3. How is the happiness of a respondent related to his/her marriage status? Define that a person is happy if the response to question is "Very happy" or "Pretty happy".
4. Does party affiliation affect the relationship you found in the last question?
5. How is marrital status related to the education of a respondent? What are possible reasons accounting for the patterns you see?
6. Explore two more interesting questions, and answer those questions using the GSS data. 

The team's exploration will be evaluated according to the  general interest and the depth of the exploration.

## Tips and Resources 
- Decide a common version of the dataset to work on
- Take a look at the [key trends](https://gssdataexplorer.norc.org/trends) to find interesting questions to explore. 
<!-- - The package `classdata` also contains a small extraction of the opinion data, called `happy`. You can play around with it to familiarize yourself with the structure of the data. However, *since this is an incomplete collection, your final answer must be based on the data extracted from the data explorer.*  -->

