---
title: "DS 202 - What you said figures"
author: "Xiongtao Dai"
ratio: 16x10
output:
  rmdshower::shower_presentation:
    self_contained: false
    katex: true
    theme: ribbon
    incremental: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
topics <- read.csv("data/topics202_21F.csv", stringsAsFactors = FALSE)
topics <- topics %>% 
    setNames(gsub('Topics.of.Interest..', '', names(topics), fixed=TRUE)) %>% 
    select(-Timestamp)
head(topics)
```


## Visualizing all topics

```{r, echo=FALSE, fig.with = 8, fig.height = 4.5}
tlong <- topics %>% gather(key='topic', value='rating')
tlong %>% 
  ggplot(aes(x = rating)) + geom_bar(aes(fill=rating)) +
  facet_wrap(~topic, ncol=5) +
  theme(legend.position="bottom")
```

## ... in the right order ...

```{r, echo=FALSE, fig.with = 8, fig.height = 4.5}
tlong <- tlong %>% mutate(
  rating = factor(rating, 
                  levels= c("Favorite", "Like it very much",
                            "Like it", "Don't like it that much"))
)
tlong %>% 
  ggplot(aes(x = rating)) + geom_bar(aes(fill=rating)) +
  facet_wrap(~topic, ncol=5) +
  theme(legend.position="bottom")
```

## ... better color scheme ...

```{r, echo=FALSE, fig.with = 8, fig.height = 4.5}
library(RColorBrewer)
cols <- brewer.pal("RdBu", n = 8)

tlong %>% 
  ggplot(aes(x = rating)) + geom_bar(aes(fill=rating)) +
  facet_wrap(~topic, ncol=5) +
  theme(legend.position="bottom") +
  scale_fill_manual(values = cols[c(8,7,6,1)])
```

## ... a different picture ...

```{r, echo=FALSE, fig.with = 8, fig.height = 4.5}
library(RColorBrewer)
cols <- brewer.pal("RdBu", n = 8)

tlong %>% 
  ggplot(aes(x = topic)) + geom_bar(aes(fill=rating)) +
  theme(legend.position="bottom") +
  scale_fill_manual(values = cols[c(8,7,6,1)])
```

## ... a different picture ...

```{r, echo=FALSE, fig.with = 8, fig.height = 4.5}
tlong %>% 
  ggplot(aes(x = topic)) + geom_bar(aes(fill=rating)) +
  theme(legend.position="bottom") +
  scale_fill_manual(values = cols[c(8,7,6,1)]) +
  coord_flip()
```

## close to a final picture

```{r, echo=FALSE, fig.with = 8, fig.height = 4.5}
labels <- unique(tlong$topics)
tlong %>% 
  ggplot(aes(x = topic)) + geom_bar(aes(fill=rating)) +
  theme(legend.position="bottom") +
  scale_fill_manual(values = cols[c(8,7,6,1)]) +
  coord_flip() + 
  theme(axis.text.y = element_blank()) +
  scale_y_reverse() +
  geom_text(aes(x = topic, label = topic), 
            y = -nrow(topics)+1, colour="white", hjust=0)
```

##  What you said:

```{r, echo=FALSE, fig.with = 8, fig.height = 4.5, warning=FALSE, message=FALSE}
# Get the cumulative preference
lvl <- tlong %>% group_by(topic) %>% mutate(rating = as.integer(rating)) %>% summarize(best = sum(rating <= 1), second = sum(rating <= 2), third = sum(rating <=3)) %>% arrange(best, second, third) %>% .$topic %>% as.character
tlong <- tlong %>% mutate(topic = factor(topic, lvl))
tlong %>% 
  ggplot(aes(x = topic)) + geom_bar(aes(fill=rating)) +
  theme(legend.position="bottom") +
  scale_fill_manual(values = cols[c(8,7,6,1)]) +
  coord_flip() + 
  theme(axis.text.y = element_blank()) +
  scale_y_reverse() +
  geom_text(aes(x = topic, label = topic), 
            y = -nrow(topics)+1, colour="white", hjust=0)
```
