---
title: "Project Proposal Feedback"
author: "Xiongtao Dai"
ratio: 16x10
output:
  rmdshower::shower_presentation:
    self_contained: false
    katex: true
    theme: ribbon
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
library(tidyverse)
```

## Final Project {.shout}

## Schedule of Presentations

[See here](https://canvas.iastate.edu/courses/85495/pages/final-project-requirements)

## Topics

- Education (Team 1, 2, 3, 17, 20)
- Income and employment (4, 16), Medicaid (7)
- Crimes (5, 6)
- Climate and environment (8, 10, 18, 24, 26)
- NFL (19, 22)
- Accidents (9, 14)
- Tweets (11), Streaming videos (13)
- Uber (12), AirBnb (25)
- Jail (15)
- Manufactures (21)
- Trading stocks (23)

## Project Plans

- A lot of intereting datasets!
- Start easy. If you team up, divide tasks, and then each teammate can look at a few aspects of data
- Coordinate different aspects to tell a coherent story
<!-- - Introduce the background to the audiences -->


## Project Presentation {.shout}


## Requirements
- You have 5 minutes if you work individually, and 8 minutes if you team up
- Timing is **very important**. Make sure your team presentation is at most 30 seconds long or short.
- Ideally, your presentation should contain a nicely made, information-rich visualization as the featured infographics. Make sure everything is legible as well!
- Organization, delivery, content, and timing: each 25%

## Presentation Format
- You will record the presentation 
  - Canvas studio
  - Zoom
- The recorded presentations are to be played during the scheduled time live
- After each presentation, the audience has 2 minutes to interact with the presenters
- [Feedback](https://forms.gle/YqMF8fTzgA3AGwar5) will be sought from the audiences after the presentation 
- You are expected to attend or watch all presentations and submit feedback (counted towards evaluation & participation)

## Project analysis

Thing to try for an interesting analysis:

- Look at different aspects of the data: spatial, temporal, changes, extremes, outliers
- Factor in other variables for making fair comparisons
- Use multiple tools and types of graphs
- Combine data sources

## A good presentation should inform the audiences ...

- the background of the dataset
- what are the questions raised
- findings and answers
- how to obtain the data
- techniques used to handle the data

## A good presentation should

- be well-organized
- have smooth delivery
- inform on many different aspect of the data
- utilize different tools to explore the data
- have pretty and informative graphs and slides


## Start early!  {.shout}

## Final Project Report

- Tell the story, not only the coding
- The report should be as readable as a blog post
- The total number of figures and tables **should not exceed 4 (or 6 if you team up)**. Include only the most interesting results, and condense information in each figure
- Each figure, table, or analysis must be accomanied by explanatory text
- Report is due on 11:59 pm, Dec 13


## Some Other Requirements

- All teammates must participates. Each will write a paragraph detailing the individual contribution to the team
- The majority of analysis need to be done in `R`
- All sources need to be cited
- Cannot repeat existing analysis on the web